"""
Django settings for croppulse_backend project.

Generated by 'django-admin startproject' using Django 5.2.10.
For more information on this file, see:
https://docs.djangoproject.com/en/5.2/topics/settings/
"""

from pathlib import Path
from datetime import timedelta
import environ
import os


# Initialize environment variables
env = environ.Env(
    DEBUG=(bool, True)
)

# Read .env file if it exists
environ.Env.read_env()
# ----------------------------------------------------------------------
# Base directory
# ----------------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent

# ----------------------------------------------------------------------
# Security
# ----------------------------------------------------------------------
SECRET_KEY = 'django-insecure-6=_dn&_=!3w6tji#g(dbk$su%k5s++-0ff&qdtru^ji6(&j9h!'
DEBUG = True
ALLOWED_HOSTS = []

# Custom User model
AUTH_USER_MODEL = 'accounts.User'

# ----------------------------------------------------------------------
# Installed apps
# ----------------------------------------------------------------------
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.gis',
    # Third-party apps
    'rest_framework',
    'rest_framework_simplejwt',
    # Your apps will be added here later
    'apps.accounts.apps.AccountsConfig',
    'apps.farmers.apps.FarmersConfig',
    'apps.farms.apps.FarmsConfig',
    'apps.satellite.apps.SatelliteConfig',
    'apps.banks.apps.BanksConfig',
    'apps.loans.apps.LoansConfig',
]

# ----------------------------------------------------------------------
# Middleware
# ----------------------------------------------------------------------
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ----------------------------------------------------------------------
# URL & WSGI configuration
# ----------------------------------------------------------------------
ROOT_URLCONF = 'croppulse_backend.urls'
WSGI_APPLICATION = 'croppulse_backend.wsgi.application'

# ----------------------------------------------------------------------
# Templates
# ----------------------------------------------------------------------
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# ----------------------------------------------------------------------
# Database
# ----------------------------------------------------------------------
DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'croppulse',
        'USER': 'koboko',
        'PASSWORD': 'KphiL2022*',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}


# ----------------------------------------------------------------------
# Password validation
# ----------------------------------------------------------------------
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# ----------------------------------------------------------------------
# Internationalization
# ----------------------------------------------------------------------
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# ----------------------------------------------------------------------
# Static files
# ----------------------------------------------------------------------
BASE_DIR = Path(__file__).resolve().parent.parent
STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# ----------------------------------------------------------------------
# Default primary key field type
# ----------------------------------------------------------------------
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# ----------------------------------------------------------------------
# REST Framework
# ----------------------------------------------------------------------
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}


MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

os.makedirs(MEDIA_ROOT / 'farmer_photos', exist_ok=True)
os.makedirs(MEDIA_ROOT / 'farmer_voice_recordings', exist_ok=True)

# ----------------------------------------------------------------------
# Simple JWT Settings
# ----------------------------------------------------------------------
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
}

# Google Earth Engine Configuration
GEE_SERVICE_ACCOUNT = env('GEE_SERVICE_ACCOUNT', default='your-service-account@project.iam.gserviceaccount.com')
GEE_PRIVATE_KEY = env('GEE_PRIVATE_KEY', default='/path/to/private-key.json')

# Celery Configuration
CELERY_BROKER_URL = env('CELERY_BROKER_URL', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = env('CELERY_RESULT_BACKEND', default='redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'Africa/Nairobi'

# Celery Beat Schedule (for periodic tasks)
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    'update-ndvi-history-daily': {
        'task': 'apps.satellite.tasks.update_ndvi_history',
        'schedule': crontab(hour=2, minute=0),  # Run daily at 2 AM
    },
    'cleanup-old-scans-monthly': {
        'task': 'apps.satellite.tasks.cleanup_old_scans',
        'schedule': crontab(day_of_month=1, hour=3, minute=0),  # First day of month at 3 AM
    },
    'generate-health-alerts-daily': {
        'task': 'apps.satellite.tasks.generate_health_alerts',
        'schedule': crontab(hour=8, minute=0),  # Run daily at 8 AM
    },
}