# Generated by Django 5.2.10 on 2026-02-06 08:43

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('api_rate_limit', models.IntegerField(default=1000, help_text='Max API calls per hour')),
                ('webhook_url', models.URLField(blank=True, help_text='Webhook URL for notifications', max_length=500)),
                ('webhook_secret', models.CharField(blank=True, help_text='Secret key for webhook signature verification', max_length=100)),
                ('max_farmers', models.IntegerField(default=10000, help_text='Maximum number of farmers this bank can manage')),
                ('max_loans_per_farmer', models.IntegerField(default=5, help_text='Maximum active loans per farmer')),
                ('min_credit_score', models.IntegerField(default=0, help_text='Minimum acceptable credit score (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('use_satellite_verification', models.BooleanField(default=True, help_text='Enable satellite verification for this bank')),
                ('use_climate_risk_assessment', models.BooleanField(default=True, help_text='Enable climate risk assessment')),
                ('use_fraud_detection', models.BooleanField(default=True, help_text='Enable fraud detection')),
                ('notification_channels', models.JSONField(blank=True, default=list, help_text='Enabled notification channels: ["email", "sms", "webhook"]')),
                ('billing_plan', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='basic', max_length=50)),
                ('monthly_api_quota', models.IntegerField(default=50000, help_text='Monthly API call quota')),
                ('custom_config', models.JSONField(blank=True, default=dict, help_text='Bank-specific custom configuration')),
                ('is_active', models.BooleanField(default=True, help_text='Is this bank configuration active')),
                ('bank', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuration', to='banks.bank')),
            ],
            options={
                'db_table': 'admin_bank_configurations',
                'ordering': ['bank'],
            },
        ),
        migrations.CreateModel(
            name='FeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(db_index=True, help_text='Unique feature identifier (e.g., "satellite_verification")', max_length=100, unique=True)),
                ('display_name', models.CharField(help_text='Human-readable feature name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Detailed description of the feature')),
                ('is_enabled', models.BooleanField(default=False, help_text='Global feature status')),
                ('is_beta', models.BooleanField(default=False, help_text='Mark as beta feature')),
                ('category', models.CharField(choices=[('verification', 'Verification'), ('analytics', 'Analytics'), ('compliance', 'Compliance'), ('notifications', 'Notifications'), ('loans', 'Loans'), ('climate', 'Climate'), ('fraud', 'Fraud Detection'), ('general', 'General')], default='general', max_length=50)),
                ('rollout_percentage', models.IntegerField(default=100, help_text='Percentage of users who can access this feature (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional configuration parameters')),
            ],
            options={
                'db_table': 'admin_feature_flags',
                'ordering': ['category', 'display_name'],
                'indexes': [models.Index(fields=['name', 'is_enabled'], name='admin_featu_name_23d42a_idx'), models.Index(fields=['category'], name='admin_featu_categor_ce4d2a_idx')],
            },
        ),
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(db_index=True, help_text='Setting key (e.g., "max_api_calls_per_hour")', max_length=100, unique=True)),
                ('value', models.TextField(help_text='Setting value (can be JSON string for complex values)')),
                ('value_type', models.CharField(choices=[('string', 'String'), ('integer', 'Integer'), ('float', 'Float'), ('boolean', 'Boolean'), ('json', 'JSON')], default='string', max_length=20)),
                ('category', models.CharField(choices=[('system', 'System'), ('api', 'API'), ('notifications', 'Notifications'), ('security', 'Security'), ('integrations', 'Integrations'), ('scoring', 'Scoring'), ('limits', 'Limits')], default='system', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Description of what this setting controls')),
                ('is_sensitive', models.BooleanField(default=False, help_text='Mark as sensitive (e.g., API keys, passwords)')),
                ('is_editable', models.BooleanField(default=True, help_text='Can be edited via admin interface')),
            ],
            options={
                'db_table': 'admin_global_settings',
                'ordering': ['category', 'key'],
                'indexes': [models.Index(fields=['category'], name='admin_globa_categor_2cb1ce_idx'), models.Index(fields=['key'], name='admin_globa_key_79f51c_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('total_api_calls', models.IntegerField(default=0)),
                ('failed_api_calls', models.IntegerField(default=0)),
                ('avg_response_time', models.FloatField(default=0.0, help_text='in milliseconds')),
                ('active_users', models.IntegerField(default=0)),
                ('new_users_today', models.IntegerField(default=0)),
                ('total_farmers', models.IntegerField(default=0)),
                ('total_farms', models.IntegerField(default=0)),
                ('total_loans', models.IntegerField(default=0)),
                ('cpu_usage', models.FloatField(default=0.0, help_text='CPU usage percentage')),
                ('memory_usage', models.FloatField(default=0.0, help_text='Memory usage percentage')),
                ('disk_usage', models.FloatField(default=0.0, help_text='Disk usage percentage')),
                ('database_status', models.CharField(choices=[('healthy', 'Healthy'), ('degraded', 'Degraded'), ('down', 'Down')], default='healthy', max_length=20)),
                ('redis_status', models.CharField(choices=[('healthy', 'Healthy'), ('degraded', 'Degraded'), ('down', 'Down')], default='healthy', max_length=20)),
                ('celery_status', models.CharField(choices=[('healthy', 'Healthy'), ('degraded', 'Degraded'), ('down', 'Down')], default='healthy', max_length=20)),
                ('gee_status', models.CharField(choices=[('healthy', 'Healthy'), ('degraded', 'Degraded'), ('down', 'Down')], default='healthy', help_text='Google Earth Engine status', max_length=20)),
                ('nasa_power_status', models.CharField(choices=[('healthy', 'Healthy'), ('degraded', 'Degraded'), ('down', 'Down')], default='healthy', help_text='NASA POWER API status', max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'System Metric',
                'verbose_name_plural': 'System Metrics',
                'db_table': 'admin_system_metrics',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='admin_syste_timesta_49b4b3_idx')],
            },
        ),
        migrations.CreateModel(
            name='APIUsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('endpoint', models.CharField(db_index=True, max_length=200)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('PATCH', 'PATCH'), ('DELETE', 'DELETE')], max_length=10)),
                ('status_code', models.IntegerField()),
                ('response_time', models.FloatField(help_text='Response time in milliseconds')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('request_size', models.IntegerField(default=0, help_text='Request size in bytes')),
                ('response_size', models.IntegerField(default=0, help_text='Response size in bytes')),
                ('error_message', models.TextField(blank=True, help_text='Error message if request failed')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('bank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_usage_logs', to='banks.bank')),
            ],
            options={
                'db_table': 'admin_api_usage_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['bank', '-timestamp'], name='admin_api_u_bank_id_46923c_idx'), models.Index(fields=['endpoint', '-timestamp'], name='admin_api_u_endpoin_c0e020_idx'), models.Index(fields=['-timestamp'], name='admin_api_u_timesta_619af5_idx')],
            },
        ),
        migrations.CreateModel(
            name='DataExportRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('export_type', models.CharField(choices=[('farmers', 'Farmers Data'), ('loans', 'Loans Data'), ('scores', 'Credit Scores'), ('satellite', 'Satellite Data'), ('compliance', 'Compliance Certificates'), ('audit_logs', 'Audit Logs'), ('full_backup', 'Full Database Backup')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('format', models.CharField(choices=[('csv', 'CSV'), ('json', 'JSON'), ('xlsx', 'Excel'), ('pdf', 'PDF')], default='csv', max_length=10)),
                ('filters', models.JSONField(blank=True, default=dict, help_text='Additional filters for the export')),
                ('file_url', models.URLField(blank=True, help_text='URL to download the exported file', max_length=500)),
                ('file_size', models.IntegerField(default=0, help_text='File size in bytes')),
                ('records_count', models.IntegerField(default=0, help_text='Number of records exported')),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When the download link expires', null=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_data_export_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['requested_by', '-created_at'], name='admin_data__request_2778c2_idx'), models.Index(fields=['status'], name='admin_data__status_ab7543_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('severity', models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=20)),
                ('category', models.CharField(choices=[('system', 'System'), ('security', 'Security'), ('performance', 'Performance'), ('data', 'Data'), ('integration', 'Integration')], default='system', max_length=50)),
                ('is_resolved', models.BooleanField(default=False, help_text='Has this alert been resolved?')),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(blank=True, help_text='Source of the alert (e.g., "celery_worker", "api_monitor")', max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional alert data')),
                ('notification_sent', models.BooleanField(default=False, help_text='Has notification been sent to admins?')),
                ('notification_sent_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_system_alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['severity', '-created_at'], name='admin_syste_severit_12d5e5_idx'), models.Index(fields=['category', 'is_resolved'], name='admin_syste_categor_26c7ae_idx'), models.Index(fields=['-created_at'], name='admin_syste_created_3f65bf_idx')],
            },
        ),
        migrations.CreateModel(
            name='TenantFeatureFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField(default=False, help_text='Override global feature status for this tenant')),
                ('custom_config', models.JSONField(blank=True, default=dict, help_text='Tenant-specific configuration')),
                ('feature_flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_overrides', to='admin_portal.featureflag')),
                ('tenant_user', models.ForeignKey(limit_choices_to={'user_type__in': ['bank', 'exporter']}, on_delete=django.db.models.deletion.CASCADE, related_name='feature_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_tenant_feature_flags',
                'ordering': ['tenant_user', 'feature_flag'],
                'unique_together': {('feature_flag', 'tenant_user')},
            },
        ),
    ]
