# Generated by Django 5.2.10 on 2026-02-04 17:16

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmers', '0002_farmernote_alter_farmer_options_and_more'),
        ('farms', '0002_alter_farm_options_alter_farmboundarypoint_options_and_more'),
        ('loans', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FraudAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(help_text="e.g., 'ghost_farm', 'duplicate_farm', 'ndvi_mismatch'", max_length=50)),
                ('severity', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('critical', 'Critical Risk')], default='medium', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('investigating', 'Under Investigation'), ('confirmed', 'Confirmed Fraud'), ('false_positive', 'False Positive'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('description', models.TextField(help_text='Details of the fraud pattern detected')),
                ('evidence', models.JSONField(help_text='Supporting data/metrics for the alert')),
                ('score_impact', models.IntegerField(default=0, help_text='How much this alert reduces the credit score')),
                ('blocks_lending', models.BooleanField(default=False, help_text='If true, farmer cannot get loans until resolved')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fraud_alerts', to='farms.farm')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fraud_alerts', to='farmers.farmer')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_fraud_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fraud_alerts',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['farmer', 'status'], name='fraud_alert_farmer__81b168_idx'), models.Index(fields=['severity', 'status'], name='fraud_alert_severit_654a2d_idx'), models.Index(fields=['-created_at'], name='fraud_alert_created_9ad20a_idx')],
            },
        ),
        migrations.CreateModel(
            name='PulseScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(help_text='Credit score from 0-1000', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('confidence_level', models.FloatField(help_text='Confidence in score accuracy (0.0-1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('farm_size_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('crop_health_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('climate_risk_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('deforestation_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('payment_history_score', models.IntegerField(default=50, help_text='50 = neutral for new farmers', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('max_loan_amount', models.DecimalField(decimal_places=2, help_text='Maximum recommended loan amount based on score', max_digits=12)),
                ('recommended_interest_rate_min', models.FloatField(help_text='Minimum recommended interest rate (%)')),
                ('recommended_interest_rate_max', models.FloatField(help_text='Maximum recommended interest rate (%)')),
                ('default_probability', models.FloatField(help_text='Estimated default probability (0-100%)')),
                ('calculation_method', models.CharField(default='v1.0', help_text='Version of scoring algorithm used', max_length=50)),
                ('factors_used', models.JSONField(help_text='List of data points used in calculation')),
                ('satellite_data_date', models.DateField(blank=True, help_text='Date of satellite data used', null=True)),
                ('climate_data_date', models.DateField(blank=True, help_text='Date of climate data used', null=True)),
                ('valid_from', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateTimeField(help_text='Score expires after this date')),
                ('is_current', models.BooleanField(default=True, help_text='True if this is the active score for the farmer')),
                ('is_frozen', models.BooleanField(default=False, help_text='True if score is frozen due to pending loan application')),
                ('frozen_at', models.DateTimeField(blank=True, help_text='When score was frozen', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pulse_scores', to='farms.farm')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pulse_scores', to='farmers.farmer')),
                ('frozen_by_loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frozen_scores', to='loans.loanapplication')),
            ],
            options={
                'db_table': 'pulse_scores',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['farmer', '-created_at'], name='pulse_score_farmer__28644b_idx'), models.Index(fields=['farm', '-created_at'], name='pulse_score_farm_id_eeb949_idx'), models.Index(fields=['is_current'], name='pulse_score_is_curr_0ad986_idx'), models.Index(fields=['is_frozen'], name='pulse_score_is_froz_328e45_idx'), models.Index(fields=['score', '-created_at'], name='pulse_score_score_a0cbc7_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScoreHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('change_from_previous', models.IntegerField(help_text='Score delta from previous day (can be negative)')),
                ('farm_size_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('crop_health_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('climate_risk_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('payment_history_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_history', to='farmers.farmer')),
            ],
            options={
                'db_table': 'score_history',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['farmer', '-date'], name='score_histo_farmer__540bd9_idx')],
                'unique_together': {('farmer', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ScoreOverride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_score', models.IntegerField()),
                ('override_score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('reason', models.CharField(choices=[('data_error', 'Data Quality Issue'), ('special_case', 'Special Circumstances'), ('fraud_detected', 'Fraud Detected'), ('manual_review', 'Manual Credit Review'), ('system_error', 'System Error'), ('appeal_approved', 'Farmer Appeal Approved')], max_length=50)),
                ('notes', models.TextField(help_text='Detailed explanation for override')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('valid_until', models.DateTimeField(help_text='Override expires after this date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_score_overrides', to=settings.AUTH_USER_MODEL)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_overrides', to='farmers.farmer')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_score_overrides', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'score_overrides',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['farmer', 'is_active'], name='score_overr_farmer__bac649_idx'), models.Index(fields=['-created_at'], name='score_overr_created_48e13a_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScoreRecalculationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger', models.CharField(choices=[('scheduled', 'Scheduled Recalculation'), ('new_satellite', 'New Satellite Data'), ('new_payment', 'New Payment Received'), ('manual', 'Manual Trigger'), ('loan_application', 'Loan Application Submitted'), ('system', 'System-Initiated')], max_length=50)),
                ('old_score', models.IntegerField(blank=True, null=True)),
                ('new_score', models.IntegerField()),
                ('score_change', models.IntegerField(help_text='new_score - old_score')),
                ('calculation_method', models.CharField(max_length=50)),
                ('factors_changed', models.JSONField(help_text='List of factors that changed since last calculation')),
                ('calculation_time_ms', models.IntegerField(help_text='Time taken to calculate score (milliseconds)')),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_recalculation_logs', to='farmers.farmer')),
            ],
            options={
                'db_table': 'score_recalculation_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['farmer', '-created_at'], name='score_recal_farmer__3d3ff3_idx'), models.Index(fields=['trigger', '-created_at'], name='score_recal_trigger_160ccd_idx'), models.Index(fields=['success'], name='score_recal_success_2118a0_idx')],
            },
        ),
    ]
