# Generated by Django 5.2.10 on 2026-02-01 10:48

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_id', models.CharField(max_length=50, unique=True)),
                ('boundary', django.contrib.gis.db.models.fields.PolygonField(geography=True, srid=4326)),
                ('center_point', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('size_acres', models.DecimalField(decimal_places=2, max_digits=10)),
                ('size_hectares', models.DecimalField(decimal_places=2, max_digits=10)),
                ('elevation', models.FloatField(blank=True, null=True)),
                ('county', models.CharField(max_length=100)),
                ('sub_county', models.CharField(max_length=100)),
                ('ward', models.CharField(max_length=100)),
                ('satellite_verified', models.BooleanField(default=False)),
                ('last_verified', models.DateTimeField(blank=True, null=True)),
                ('ownership_document', models.FileField(blank=True, null=True, upload_to='land_documents/')),
                ('is_primary', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farms', to='farmers.farmer')),
            ],
            options={
                'db_table': 'farms',
            },
        ),
        migrations.CreateModel(
            name='FarmBoundaryPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('sequence', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boundary_points', to='farms.farm')),
            ],
            options={
                'db_table': 'farm_boundary_points',
                'ordering': ['sequence'],
            },
        ),
        migrations.AddIndex(
            model_name='farm',
            index=models.Index(fields=['farmer', 'is_primary'], name='farms_farmer__c88fac_idx'),
        ),
    ]
