# Generated by Django 5.2.10 on 2026-02-02 20:55

import django.contrib.gis.db.models.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0002_farmernote_alter_farmer_options_and_more'),
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farm',
            options={'ordering': ['-is_primary', '-created_at'], 'verbose_name': 'Farm', 'verbose_name_plural': 'Farms'},
        ),
        migrations.AlterModelOptions(
            name='farmboundarypoint',
            options={'ordering': ['sequence'], 'verbose_name': 'Farm Boundary Point', 'verbose_name_plural': 'Farm Boundary Points'},
        ),
        migrations.AddField(
            model_name='farm',
            name='boundary_accuracy_meters',
            field=models.FloatField(blank=True, help_text='Estimated boundary accuracy in meters', null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='boundary_source',
            field=models.CharField(choices=[('gps_walk', 'GPS Walk'), ('mobile_map', 'Mobile Map Drawing'), ('satellite_trace', 'Satellite Image Trace'), ('survey', 'Professional Survey')], default='mobile_map', max_length=50),
        ),
        migrations.AddField(
            model_name='farm',
            name='irrigation_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farm',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='land_ownership_type',
            field=models.CharField(choices=[('owned', 'Owned'), ('leased', 'Leased'), ('communal', 'Communal'), ('family', 'Family Land')], default='owned', max_length=50),
        ),
        migrations.AddField(
            model_name='farm',
            name='slope_percentage',
            field=models.FloatField(blank=True, help_text='Average slope percentage', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MinValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='farm',
            name='soil_type',
            field=models.CharField(blank=True, help_text='Primary soil type (e.g., clay, loam, sandy)', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='verification_confidence',
            field=models.FloatField(blank=True, help_text='Satellite verification confidence score (0.0-1.0)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MinValueValidator(1.0)]),
        ),
        migrations.AddField(
            model_name='farm',
            name='water_source',
            field=models.CharField(blank=True, help_text='e.g., River, Borehole, Rain-fed', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='farmboundarypoint',
            name='accuracy',
            field=models.FloatField(blank=True, help_text='GPS accuracy in meters', null=True),
        ),
        migrations.AddField(
            model_name='farmboundarypoint',
            name='altitude',
            field=models.FloatField(blank=True, help_text='Altitude in meters', null=True),
        ),
        migrations.AddField(
            model_name='farmboundarypoint',
            name='recorded_at',
            field=models.DateTimeField(blank=True, help_text='When this point was recorded', null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='boundary',
            field=django.contrib.gis.db.models.fields.PolygonField(geography=True, help_text='Farm boundary polygon', srid=4326),
        ),
        migrations.AlterField(
            model_name='farm',
            name='center_point',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, help_text='Farm center GPS coordinates', srid=4326),
        ),
        migrations.AlterField(
            model_name='farm',
            name='county',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='farm',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='elevation',
            field=models.FloatField(blank=True, help_text='Elevation in meters above sea level', null=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='farm_id',
            field=models.CharField(db_index=True, help_text='Unique farm identifier (e.g., FARM-882-01)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='farm',
            name='is_primary',
            field=models.BooleanField(default=True, help_text='Primary farm for this farmer'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='ownership_document',
            field=models.FileField(blank=True, null=True, upload_to='land_documents/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='farm',
            name='satellite_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='farm',
            name='size_acres',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='farm',
            name='size_hectares',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='farmboundarypoint',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(geography=True, help_text='GPS point coordinates', srid=4326),
        ),
        migrations.AlterField(
            model_name='farmboundarypoint',
            name='sequence',
            field=models.IntegerField(help_text='Order of points in polygon (0-indexed)'),
        ),
        migrations.AlterUniqueTogether(
            name='farmboundarypoint',
            unique_together={('farm', 'sequence')},
        ),
        migrations.AddIndex(
            model_name='farm',
            index=models.Index(fields=['county', 'sub_county'], name='farms_county_041481_idx'),
        ),
        migrations.AddIndex(
            model_name='farm',
            index=models.Index(fields=['satellite_verified'], name='farms_satelli_a43242_idx'),
        ),
        migrations.AddIndex(
            model_name='farm',
            index=models.Index(fields=['is_active'], name='farms_is_acti_dfab85_idx'),
        ),
        migrations.AddIndex(
            model_name='farmboundarypoint',
            index=models.Index(fields=['farm', 'sequence'], name='farm_bounda_farm_id_ab4e3b_idx'),
        ),
    ]
