# Generated by Django 5.2.10 on 2026-02-05 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_alter_farm_options_alter_farmboundarypoint_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='boundary_match_score',
            field=models.FloatField(blank=True, help_text='GPS vs Satellite boundary match score', null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='gps_trace_points',
            field=models.JSONField(default=list, help_text='Raw GPS points from mobile trace'),
        ),
        migrations.AddField(
            model_name='farm',
            name='gps_trace_quality',
            field=models.FloatField(blank=True, help_text='GPS trace quality score (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='satellite_confidence_score',
            field=models.FloatField(blank=True, help_text='Satellite verification confidence (0-100)', null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='satellite_verification_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farm',
            name='size_verification_status',
            field=models.CharField(choices=[('verified', 'Verified'), ('discrepancy', 'Size Discrepancy'), ('pending', 'Pending Verification')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='farm',
            name='satellite_verified',
            field=models.BooleanField(default=False),
        ),
    ]
