# Generated by Django 5.2.10 on 2026-02-06 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0003_farm_boundary_match_score_farm_gps_trace_points_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='boundary_accuracy_meters',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='boundary_match_score',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='boundary_source',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='satellite_confidence_score',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='satellite_verification_date',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='size_verification_status',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='slope_percentage',
        ),
        migrations.RemoveField(
            model_name='farm',
            name='soil_type',
        ),
        migrations.AlterField(
            model_name='farm',
            name='satellite_verified',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
