# Generated by Django 5.2.10 on 2026-02-05 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farmers', '0002_farmernote_alter_farmer_options_and_more'),
        ('farms', '0002_alter_farm_options_alter_farmboundarypoint_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeforestationCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_date', models.DateField()),
                ('analysis_start_date', models.DateField()),
                ('analysis_end_date', models.DateField()),
                ('deforestation_detected', models.BooleanField(default=False)),
                ('forest_cover_percentage', models.FloatField()),
                ('change_in_forest_cover', models.FloatField()),
                ('satellite_imagery_urls', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deforestation_checks', to='farms.farm')),
            ],
            options={
                'db_table': 'deforestation_checks',
            },
        ),
        migrations.CreateModel(
            name='ExportPassport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passport_id', models.CharField(max_length=50, unique=True)),
                ('dds_reference_number', models.CharField(max_length=100, unique=True)),
                ('baseline_date', models.DateField(default='2020-12-31')),
                ('deforestation_status', models.CharField(max_length=50)),
                ('satellite_proof_url', models.URLField(max_length=500)),
                ('gps_coordinates', models.JSONField()),
                ('farm_size_hectares', models.DecimalField(decimal_places=2, max_digits=10)),
                ('land_ownership_verified', models.BooleanField(default=False)),
                ('land_document_url', models.URLField(blank=True, max_length=500, null=True)),
                ('audit_trail', models.JSONField(default=list)),
                ('issued_date', models.DateField(auto_now_add=True)),
                ('valid_until', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_passports', to='farms.farm')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='export_passports', to='farmers.farmer')),
            ],
            options={
                'db_table': 'export_passports',
                'indexes': [models.Index(fields=['farmer', '-issued_date'], name='export_pass_farmer__a97f19_idx')],
            },
        ),
    ]
