# Generated by Django 5.2.10 on 2026-02-09 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('VERIFY', 'Verified'), ('APPROVE', 'Approved'), ('REJECT', 'Rejected'), ('EXPORT', 'Exported'), ('BLOCKCHAIN_ANCHOR', 'Blockchain Anchored'), ('DEFORESTATION_CHECK', 'Deforestation Check')], max_length=50),
        ),
        migrations.AlterField(
            model_name='deforestationcheck',
            name='baseline_date',
            field=models.DateField(default=datetime.date(2020, 12, 31)),
        ),
        migrations.AlterField(
            model_name='exportpassport',
            name='baseline_date',
            field=models.DateField(default=datetime.date(2020, 12, 31), help_text='EUDR baseline cutoff date'),
        ),
        migrations.AlterField(
            model_name='exportpassport',
            name='commodity_code',
            field=models.CharField(help_text='CN/HS Code', max_length=20),
        ),
        migrations.AlterField(
            model_name='exportpassport',
            name='operator_name',
            field=models.CharField(help_text='EU Operator/Trader Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='exportpassport',
            name='passport_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='exportpassport',
            name='valid_until',
            field=models.DateField(blank=True, help_text='Passport expires after 1 year typically', null=True),
        ),
    ]
