# Generated by Django 5.2.10 on 2026-02-06 12:45

import core.mixins.tenant_mixin
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
        ('farmers', '0002_farmernote_alter_farmer_options_and_more'),
        ('farms', '0004_remove_farm_boundary_accuracy_meters_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('EXPORT_PASSPORT', 'Export Passport'), ('DEFORESTATION_CHECK', 'Deforestation Check'), ('COMPLIANCE_DOCUMENT', 'Compliance Document')], max_length=50)),
                ('entity_id', models.UUIDField()),
                ('user_id', models.CharField(max_length=255)),
                ('user_name', models.CharField(max_length=255)),
                ('user_role', models.CharField(blank=True, max_length=100, null=True)),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted'), ('VERIFY', 'Verified'), ('APPROVE', 'Approved'), ('REJECT', 'Rejected'), ('EXPORT', 'Exported'), ('BLOCKCHAIN_ANCHOR', 'Blockchain Anchored')], max_length=50)),
                ('changes', models.JSONField(default=dict, help_text='Before/after values for updates')),
                ('reason', models.TextField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs_compliance',
                'ordering': ['-timestamp'],
            },
            bases=(core.mixins.tenant_mixin.TenantMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ComplianceDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('LAND_TITLE', 'Land Title'), ('SATELLITE_REPORT', 'Satellite Analysis Report'), ('AUDIT_CERTIFICATE', 'Audit Certificate'), ('FARMERS_DECLARATION', "Farmer's Declaration"), ('PHOTO_EVIDENCE', 'Photo Evidence'), ('GPS_TRACE', 'GPS Trace'), ('OTHER', 'Other')], max_length=50)),
                ('document_name', models.CharField(max_length=255)),
                ('document_file', models.FileField(upload_to='compliance/documents/')),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('file_hash', models.CharField(blank=True, help_text='SHA-256 hash', max_length=64, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.CharField(max_length=255)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_by', models.CharField(blank=True, max_length=255, null=True)),
                ('verified_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Compliance Document',
                'verbose_name_plural': 'Compliance Documents',
                'db_table': 'compliance_documents',
                'ordering': ['-upload_date'],
            },
            bases=(core.mixins.tenant_mixin.TenantMixin, models.Model),
        ),
        migrations.CreateModel(
            name='TranslationCache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_language', models.CharField(max_length=10)),
                ('target_language', models.CharField(max_length=10)),
                ('source_text', models.TextField()),
                ('translated_text', models.TextField()),
                ('cache_key', models.CharField(db_index=True, max_length=64, unique=True)),
                ('hit_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'translation_cache',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='deforestationcheck',
            options={'ordering': ['-check_date'], 'verbose_name': 'Deforestation Check', 'verbose_name_plural': 'Deforestation Checks'},
        ),
        migrations.AlterModelOptions(
            name='exportpassport',
            options={'ordering': ['-created_at'], 'verbose_name': 'Export Passport', 'verbose_name_plural': 'Export Passports'},
        ),
        migrations.AddField(
            model_name='deforestationcheck',
            name='analysis_metadata',
            field=models.JSONField(default=dict, help_text='Additional analysis parameters and results'),
        ),
        migrations.AddField(
            model_name='deforestationcheck',
            name='analysis_method',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deforestationcheck',
            name='baseline_date',
            field=models.DateField(default='2020-12-31'),
        ),
        migrations.AddField(
            model_name='deforestationcheck',
            name='baseline_forest_cover',
            field=models.FloatField(blank=True, help_text='Forest cover at baseline date', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='deforestationcheck',
            name='check_type',
            field=models.CharField(choices=[('INITIAL', 'Initial Assessment'), ('PERIODIC', 'Periodic Review'), ('TRIGGERED', 'Alert-Triggered'), ('RENEWAL', 'Passport Renewal')], default='INITIAL', max_length=50),
        ),
        migrations.AddField(
            model_name='deforestationcheck',
            name='cloud_cover_percentage',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='deforestationcheck',
            name='confidence_score',
            field=models.FloatField(blank=True, help_text='Confidence in analysis result (0-1)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='deforestationcheck',
            name='evidence_urls',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='deforestationcheck',
            name='export_passport',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deforestation_checks', to='compliance.exportpassport'),
        ),
        migrations.AddField(
            model_name='deforestationcheck',
            name='forest_loss_hectares',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Estimated forest loss in hectares', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='deforestationcheck',
            name='ndvi_baseline',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deforestationcheck',
            name='ndvi_change',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deforestationcheck',
            name='ndvi_current',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deforestationcheck',
            name='report_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='deforestationcheck',
            name='result',
            field=models.CharField(blank=True, choices=[('CLEAR', 'Clear - No Deforestation'), ('WARNING', 'Warning - Minor Changes'), ('VIOLATION', 'Violation - Deforestation Detected'), ('INCONCLUSIVE', 'Inconclusive - Needs Review')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='deforestationcheck',
            name='reviewed_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='deforestationcheck',
            name='reviewed_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deforestationcheck',
            name='reviewer_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deforestationcheck',
            name='risk_factors',
            field=models.JSONField(default=list, help_text='List of identified risk factors'),
        ),
        migrations.AddField(
            model_name='deforestationcheck',
            name='risk_score',
            field=models.IntegerField(default=0, help_text='Deforestation risk score (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='deforestationcheck',
            name='satellite_provider',
            field=models.CharField(choices=[('SENTINEL2', 'Sentinel-2'), ('LANDSAT8', 'Landsat 8'), ('PLANET', 'Planet Labs'), ('GLOBAL_FOREST_WATCH', 'Global Forest Watch')], default='SENTINEL2', max_length=50),
        ),
        migrations.AddField(
            model_name='deforestationcheck',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Analysis Pending'), ('IN_PROGRESS', 'Analysis In Progress'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('REQUIRES_REVIEW', 'Requires Manual Review')], default='PENDING', max_length=50),
        ),
        migrations.AddField(
            model_name='deforestationcheck',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='exportpassport',
            name='blockchain_hash',
            field=models.CharField(blank=True, db_index=True, max_length=66, null=True),
        ),
        migrations.AddField(
            model_name='exportpassport',
            name='blockchain_network',
            field=models.CharField(blank=True, choices=[('ETHEREUM', 'Ethereum'), ('POLYGON', 'Polygon'), ('AVALANCHE', 'Avalanche'), ('CELO', 'Celo')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='exportpassport',
            name='blockchain_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exportpassport',
            name='blockchain_tx_hash',
            field=models.CharField(blank=True, max_length=66, null=True),
        ),
        migrations.AddField(
            model_name='exportpassport',
            name='centroid_latitude',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='exportpassport',
            name='centroid_longitude',
            field=models.DecimalField(decimal_places=7, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='exportpassport',
            name='commodity_code',
            field=models.CharField(default='0000', help_text='CN/HS Code', max_length=20),
        ),
        migrations.AddField(
            model_name='exportpassport',
            name='commodity_type',
            field=models.CharField(choices=[('COFFEE', 'Coffee'), ('COCOA', 'Cocoa'), ('PALM_OIL', 'Palm Oil'), ('CATTLE', 'Cattle'), ('WOOD', 'Wood'), ('RUBBER', 'Rubber'), ('SOY', 'Soy')], default='COFFEE', max_length=50),
        ),
        migrations.AddField(
            model_name='exportpassport',
            name='estimated_production_kg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='exportpassport',
            name='harvest_season',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='exportpassport',
            name='internal_reference',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='exportpassport',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exportpassport',
            name='land_document_type',
            field=models.CharField(blank=True, choices=[('TITLE_DEED', 'Title Deed'), ('LEASE_AGREEMENT', 'Lease Agreement'), ('CUSTOMARY_CERT', 'Customary Certificate'), ('COOPERATIVE_CERT', 'Cooperative Certificate')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='exportpassport',
            name='land_tenure_type',
            field=models.CharField(blank=True, choices=[('FREEHOLD', 'Freehold'), ('LEASEHOLD', 'Leasehold'), ('CUSTOMARY', 'Customary Rights'), ('COMMUNAL', 'Communal Land'), ('COOPERATIVE', 'Cooperative')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='exportpassport',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('de', 'German'), ('es', 'Spanish'), ('sw', 'Swahili')], default='en', max_length=10),
        ),
        migrations.AddField(
            model_name='exportpassport',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exportpassport',
            name='operator_eori',
            field=models.CharField(blank=True, help_text='EORI Number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='exportpassport',
            name='operator_name',
            field=models.CharField(default='Unknown', help_text='EU Operator/Trader Name', max_length=255),
        ),
        migrations.AddField(
            model_name='exportpassport',
            name='pdf_document',
            field=models.FileField(blank=True, null=True, upload_to='compliance/passports/'),
        ),
        migrations.AddField(
            model_name='exportpassport',
            name='plot_area_sqm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='exportpassport',
            name='qr_data',
            field=models.JSONField(blank=True, help_text='Data encoded in QR code', null=True),
        ),
        migrations.AddField(
            model_name='exportpassport',
            name='risk_level',
            field=models.CharField(choices=[('LOW', 'Low Risk'), ('STANDARD', 'Standard Risk'), ('HIGH', 'High Risk')], default='STANDARD', max_length=20),
        ),
        migrations.AddField(
            model_name='exportpassport',
            name='satellite_analysis_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exportpassport',
            name='verified_by',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exportpassport',
            name='verified_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deforestationcheck',
            name='analysis_end_date',
            field=models.DateField(help_text='End of analysis period'),
        ),
        migrations.AlterField(
            model_name='deforestationcheck',
            name='analysis_start_date',
            field=models.DateField(help_text='Start of analysis period'),
        ),
        migrations.AlterField(
            model_name='deforestationcheck',
            name='change_in_forest_cover',
            field=models.FloatField(help_text='Percentage point change (can be negative)'),
        ),
        migrations.AlterField(
            model_name='deforestationcheck',
            name='check_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='deforestationcheck',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='deforestationcheck',
            name='forest_cover_percentage',
            field=models.FloatField(help_text='Current forest cover percentage', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='deforestationcheck',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='deforestationcheck',
            name='satellite_imagery_urls',
            field=models.JSONField(default=list, help_text='URLs to satellite imagery used in analysis'),
        ),
        migrations.AlterField(
            model_name='exportpassport',
            name='audit_trail',
            field=models.JSONField(default=list, help_text='Chronological log of all verification steps and updates'),
        ),
        migrations.AlterField(
            model_name='exportpassport',
            name='baseline_date',
            field=models.DateField(default='2020-12-31', help_text='EUDR baseline cutoff date'),
        ),
        migrations.AlterField(
            model_name='exportpassport',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='exportpassport',
            name='dds_reference_number',
            field=models.CharField(db_index=True, help_text='Due Diligence Statement Reference Number', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='exportpassport',
            name='deforestation_status',
            field=models.CharField(choices=[('CLEAR', 'Clear - No Deforestation'), ('UNDER_REVIEW', 'Under Review'), ('FLAGGED', 'Flagged - Deforestation Detected'), ('REMEDIATED', 'Remediated')], default='UNDER_REVIEW', max_length=50),
        ),
        migrations.AlterField(
            model_name='exportpassport',
            name='farm_size_hectares',
            field=models.DecimalField(decimal_places=4, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='exportpassport',
            name='gps_coordinates',
            field=models.JSONField(default=list, help_text='Farm corner coordinates: [{lat, lng}, ...]'),
        ),
        migrations.AlterField(
            model_name='exportpassport',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='exportpassport',
            name='passport_id',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='exportpassport',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='compliance/qr_codes/'),
        ),
        migrations.AlterField(
            model_name='exportpassport',
            name='satellite_proof_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='exportpassport',
            name='valid_until',
            field=models.DateField(help_text='Passport expires after 1 year typically'),
        ),
        migrations.AddIndex(
            model_name='deforestationcheck',
            index=models.Index(fields=['farm', '-check_date'], name='deforestati_farm_id_10bc23_idx'),
        ),
        migrations.AddIndex(
            model_name='deforestationcheck',
            index=models.Index(fields=['status', 'result'], name='deforestati_status_1b14fa_idx'),
        ),
        migrations.AddIndex(
            model_name='deforestationcheck',
            index=models.Index(fields=['deforestation_detected'], name='deforestati_defores_b929db_idx'),
        ),
        migrations.AddIndex(
            model_name='exportpassport',
            index=models.Index(fields=['deforestation_status', 'is_active'], name='export_pass_defores_091aef_idx'),
        ),
        migrations.AddIndex(
            model_name='exportpassport',
            index=models.Index(fields=['dds_reference_number'], name='export_pass_dds_ref_a9d933_idx'),
        ),
        migrations.AddIndex(
            model_name='exportpassport',
            index=models.Index(fields=['blockchain_hash'], name='export_pass_blockch_4a1cd9_idx'),
        ),
        migrations.AddIndex(
            model_name='exportpassport',
            index=models.Index(fields=['-created_at'], name='export_pass_created_47c7b8_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['entity_type', 'entity_id'], name='audit_logs__entity__78cbf5_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['-timestamp'], name='audit_logs__timesta_85156c_idx'),
        ),
        migrations.AddIndex(
            model_name='auditlog',
            index=models.Index(fields=['user_id', '-timestamp'], name='audit_logs__user_id_64c02d_idx'),
        ),
        migrations.AddField(
            model_name='compliancedocument',
            name='export_passport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='compliance.exportpassport'),
        ),
        migrations.AddIndex(
            model_name='translationcache',
            index=models.Index(fields=['cache_key'], name='translation_cache_k_da1ec9_idx'),
        ),
        migrations.AddIndex(
            model_name='translationcache',
            index=models.Index(fields=['expires_at'], name='translation_expires_86386a_idx'),
        ),
    ]
