# Generated by Django 5.2.10 on 2026-02-04 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0002_alter_farm_options_alter_farmboundarypoint_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClimateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('temperature_max', models.FloatField()),
                ('temperature_min', models.FloatField()),
                ('temperature_avg', models.FloatField()),
                ('rainfall', models.FloatField()),
                ('rainfall_probability', models.FloatField()),
                ('humidity', models.FloatField()),
                ('wind_speed', models.FloatField()),
                ('solar_radiation', models.FloatField(blank=True, null=True)),
                ('data_source', models.CharField(default='NASA_POWER', max_length=50)),
                ('is_forecast', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climate_data', to='farms.farm')),
            ],
            options={
                'db_table': 'climate_data',
                'indexes': [models.Index(fields=['farm', '-date'], name='climate_dat_farm_id_1e3555_idx')],
                'unique_together': {('farm', 'date')},
            },
        ),
        migrations.CreateModel(
            name='ClimateRiskAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_date', models.DateField(auto_now_add=True)),
                ('drought_risk', models.FloatField()),
                ('flood_risk', models.FloatField()),
                ('heat_stress_risk', models.FloatField()),
                ('overall_climate_risk', models.FloatField()),
                ('analysis_start_date', models.DateField()),
                ('analysis_end_date', models.DateField()),
                ('historical_rainfall_avg', models.FloatField()),
                ('current_season_rainfall', models.FloatField()),
                ('rainfall_deviation_percentage', models.FloatField()),
                ('recommendations', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_assessments', to='farms.farm')),
            ],
            options={
                'db_table': 'climate_risk_assessments',
                'indexes': [models.Index(fields=['farm', '-assessment_date'], name='climate_ris_farm_id_e39b62_idx')],
            },
        ),
    ]
