# Generated by Django 5.2.10 on 2026-02-01 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pulse_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('id_number', models.CharField(max_length=50, unique=True)),
                ('county', models.CharField(max_length=100)),
                ('sub_county', models.CharField(max_length=100)),
                ('nearest_town', models.CharField(max_length=100)),
                ('years_farming', models.IntegerField()),
                ('primary_crop', models.CharField(max_length=100)),
                ('secondary_crops', models.JSONField(default=list)),
                ('voice_signature', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='farmer_photos/')),
                ('onboarding_completed', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='farmer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'farmers',
            },
        ),
        migrations.CreateModel(
            name='VoiceRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio_file', models.FileField(upload_to='voice_recordings/')),
                ('transcript', models.TextField()),
                ('detected_language', models.CharField(max_length=20)),
                ('confidence_score', models.FloatField()),
                ('processed_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voice_recordings', to='farmers.farmer')),
            ],
            options={
                'db_table': 'voice_registrations',
            },
        ),
        migrations.AddIndex(
            model_name='farmer',
            index=models.Index(fields=['pulse_id'], name='farmers_pulse_i_1db747_idx'),
        ),
        migrations.AddIndex(
            model_name='farmer',
            index=models.Index(fields=['county', 'sub_county'], name='farmers_county_22dcb2_idx'),
        ),
    ]
