# Generated by Django 5.2.10 on 2026-02-02 15:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farmers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('general', 'General'), ('fraud_alert', 'Fraud Alert'), ('verification', 'Verification'), ('loan_application', 'Loan Application'), ('customer_service', 'Customer Service')], default='general', max_length=50)),
                ('content', models.TextField()),
                ('is_internal', models.BooleanField(default=True, help_text='If True, not visible to farmer')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'farmer_notes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='farmer',
            options={'ordering': ['-created_at'], 'verbose_name': 'Farmer', 'verbose_name_plural': 'Farmers'},
        ),
        migrations.AlterModelOptions(
            name='voiceregistration',
            options={'ordering': ['-created_at'], 'verbose_name': 'Voice Registration', 'verbose_name_plural': 'Voice Registrations'},
        ),
        migrations.AddField(
            model_name='farmer',
            name='farming_method',
            field=models.CharField(choices=[('traditional', 'Traditional'), ('organic', 'Organic'), ('conventional', 'Conventional'), ('mixed', 'Mixed')], default='traditional', max_length=50),
        ),
        migrations.AddField(
            model_name='farmer',
            name='fraud_notes',
            field=models.TextField(blank=True, help_text='Internal notes about fraud checks', null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='fraud_status',
            field=models.CharField(choices=[('clean', 'Clean'), ('flagged', 'Flagged'), ('under_review', 'Under Review'), ('verified', 'Verified Clean'), ('suspended', 'Suspended')], db_index=True, default='clean', max_length=20),
        ),
        migrations.AddField(
            model_name='farmer',
            name='irrigation_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='farmer',
            name='last_fraud_check',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Home/primary location latitude', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, help_text='Home/primary location longitude', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='onboarding_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='farmer',
            name='preferred_language',
            field=models.CharField(choices=[('en', 'English'), ('sw', 'Swahili'), ('ki', 'Kikuyu')], default='sw', max_length=10),
        ),
        migrations.AddField(
            model_name='farmer',
            name='referral_source',
            field=models.CharField(blank=True, help_text='How farmer heard about CropPulse', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='voiceregistration',
            name='audio_duration',
            field=models.FloatField(blank=True, help_text='Duration in seconds', null=True),
        ),
        migrations.AddField(
            model_name='voiceregistration',
            name='audio_format',
            field=models.CharField(blank=True, help_text='e.g., mp3, wav, ogg', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='voiceregistration',
            name='audio_size',
            field=models.IntegerField(blank=True, help_text='File size in bytes', null=True),
        ),
        migrations.AddField(
            model_name='voiceregistration',
            name='field_confidence',
            field=models.JSONField(default=dict, help_text='Confidence scores per extracted field'),
        ),
        migrations.AddField(
            model_name='voiceregistration',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voiceregistration',
            name='processing_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voiceregistration',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='county',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='id_number',
            field=models.CharField(db_index=True, help_text='National ID or Passport number', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='onboarding_completed',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='farmer_photos/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='primary_crop',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='pulse_id',
            field=models.CharField(db_index=True, help_text='Unique Pulse ID (e.g., CP-882-NK)', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='secondary_crops',
            field=models.JSONField(default=list, help_text='List of secondary crops, e.g., ["beans", "vegetables"]'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='voice_signature',
            field=models.TextField(blank=True, help_text='Voice biometric hash', null=True),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='years_farming',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(80)]),
        ),
        migrations.AlterField(
            model_name='voiceregistration',
            name='audio_file',
            field=models.FileField(help_text='Original audio recording', upload_to='voice_recordings/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='voiceregistration',
            name='confidence_score',
            field=models.FloatField(help_text='Transcription confidence (0.0-1.0)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)]),
        ),
        migrations.AlterField(
            model_name='voiceregistration',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='voiceregistration',
            name='detected_language',
            field=models.CharField(help_text='Detected language code (en, sw, ki)', max_length=20),
        ),
        migrations.AlterField(
            model_name='voiceregistration',
            name='processed_data',
            field=models.JSONField(default=dict, help_text='Structured data extracted from voice'),
        ),
        migrations.AlterField(
            model_name='voiceregistration',
            name='transcript',
            field=models.TextField(help_text='Full transcription of audio'),
        ),
        migrations.AddIndex(
            model_name='farmer',
            index=models.Index(fields=['primary_crop'], name='farmers_primary_cda243_idx'),
        ),
        migrations.AddIndex(
            model_name='farmer',
            index=models.Index(fields=['fraud_status', 'is_active'], name='farmers_fraud_s_543e62_idx'),
        ),
        migrations.AddIndex(
            model_name='farmer',
            index=models.Index(fields=['user', 'is_active'], name='farmers_user_id_f9c1ac_idx'),
        ),
        migrations.AddIndex(
            model_name='voiceregistration',
            index=models.Index(fields=['farmer', '-created_at'], name='voice_regis_farmer__11b446_idx'),
        ),
        migrations.AddIndex(
            model_name='voiceregistration',
            index=models.Index(fields=['detected_language'], name='voice_regis_detecte_161f08_idx'),
        ),
        migrations.AddIndex(
            model_name='voiceregistration',
            index=models.Index(fields=['processing_status'], name='voice_regis_process_fd5d83_idx'),
        ),
        migrations.AddField(
            model_name='farmernote',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='farmer_notes_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='farmernote',
            name='farmer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='farmers.farmer'),
        ),
        migrations.AddIndex(
            model_name='farmernote',
            index=models.Index(fields=['farmer', '-created_at'], name='farmer_note_farmer__f35dad_idx'),
        ),
        migrations.AddIndex(
            model_name='farmernote',
            index=models.Index(fields=['note_type'], name='farmer_note_note_ty_1aa4e2_idx'),
        ),
    ]
