# Generated by Django 5.2.10 on 2026-02-01 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SatelliteScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_id', models.CharField(max_length=100, unique=True)),
                ('satellite_type', models.CharField(choices=[('sentinel1', 'Sentinel-1 SAR'), ('sentinel2', 'Sentinel-2 Optical'), ('landsat', 'Landsat')], max_length=20)),
                ('acquisition_date', models.DateTimeField()),
                ('processing_date', models.DateTimeField(auto_now_add=True)),
                ('image_url', models.URLField(max_length=500)),
                ('cloud_cover_percentage', models.FloatField()),
                ('sar_penetrated_clouds', models.BooleanField(default=False)),
                ('ndvi', models.FloatField(blank=True, null=True)),
                ('evi', models.FloatField(blank=True, null=True)),
                ('savi', models.FloatField(blank=True, null=True)),
                ('soil_moisture', models.FloatField(blank=True, null=True)),
                ('crop_stage', models.CharField(blank=True, max_length=100, null=True)),
                ('crop_health_status', models.CharField(max_length=50)),
                ('verified_farm_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('matches_declared_size', models.BooleanField(default=True)),
                ('raw_satellite_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satellite_scans', to='farms.farm')),
            ],
            options={
                'db_table': 'satellite_scans',
            },
        ),
        migrations.CreateModel(
            name='NDVIHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ndvi_value', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ndvi_history', to='farms.farm')),
                ('satellite_scan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='satellite.satellitescan')),
            ],
            options={
                'db_table': 'ndvi_history',
            },
        ),
        migrations.AddIndex(
            model_name='satellitescan',
            index=models.Index(fields=['farm', '-acquisition_date'], name='satellite_s_farm_id_817463_idx'),
        ),
        migrations.AddIndex(
            model_name='ndvihistory',
            index=models.Index(fields=['farm', '-date'], name='ndvi_histor_farm_id_fec1df_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='ndvihistory',
            unique_together={('farm', 'date')},
        ),
    ]
