# Generated by Django 5.2.10 on 2026-02-03 04:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_alter_farm_options_alter_farmboundarypoint_options_and_more'),
        ('satellite', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ndvihistory',
            options={'ordering': ['-date'], 'verbose_name': 'NDVI History', 'verbose_name_plural': 'NDVI History'},
        ),
        migrations.AlterModelOptions(
            name='satellitescan',
            options={'ordering': ['-acquisition_date'], 'verbose_name': 'Satellite Scan', 'verbose_name_plural': 'Satellite Scans'},
        ),
        migrations.AddField(
            model_name='ndvihistory',
            name='evi_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ndvihistory',
            name='rainfall_mm',
            field=models.FloatField(blank=True, help_text='Rainfall in mm', null=True),
        ),
        migrations.AddField(
            model_name='ndvihistory',
            name='savi_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ndvihistory',
            name='soil_moisture',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ndvihistory',
            name='temperature',
            field=models.FloatField(blank=True, help_text='Temperature in Celsius', null=True),
        ),
        migrations.AddField(
            model_name='satellitescan',
            name='clear_pixel_percentage',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='satellitescan',
            name='cloud_mask_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='satellitescan',
            name='data_quality_score',
            field=models.IntegerField(blank=True, help_text='Overall data quality score (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='satellitescan',
            name='msavi',
            field=models.FloatField(blank=True, help_text='Modified Soil Adjusted Vegetation Index', null=True),
        ),
        migrations.AddField(
            model_name='satellitescan',
            name='ndwi',
            field=models.FloatField(blank=True, help_text='Normalized Difference Water Index', null=True, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AddField(
            model_name='satellitescan',
            name='orbit_direction',
            field=models.CharField(blank=True, help_text='Ascending or Descending', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='satellitescan',
            name='processing_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='satellitescan',
            name='processing_status',
            field=models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=20),
        ),
        migrations.AddField(
            model_name='satellitescan',
            name='resolution_meters',
            field=models.FloatField(blank=True, help_text='Spatial resolution in meters', null=True),
        ),
        migrations.AddField(
            model_name='satellitescan',
            name='size_difference_percentage',
            field=models.FloatField(blank=True, help_text='Percentage difference between declared and verified size', null=True),
        ),
        migrations.AddField(
            model_name='satellitescan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='satellitescan',
            name='vh_backscatter',
            field=models.FloatField(blank=True, help_text='VH polarization backscatter in dB', null=True),
        ),
        migrations.AddField(
            model_name='satellitescan',
            name='vh_vv_ratio',
            field=models.FloatField(blank=True, help_text='VH/VV ratio for crop discrimination', null=True),
        ),
        migrations.AddField(
            model_name='satellitescan',
            name='vv_backscatter',
            field=models.FloatField(blank=True, help_text='VV polarization backscatter in dB', null=True),
        ),
        migrations.AlterField(
            model_name='ndvihistory',
            name='date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='ndvihistory',
            name='ndvi_value',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='ndvihistory',
            name='satellite_scan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='satellite.satellitescan'),
        ),
        migrations.AlterField(
            model_name='satellitescan',
            name='acquisition_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='satellitescan',
            name='cloud_cover_percentage',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='satellitescan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='satellitescan',
            name='crop_health_status',
            field=models.CharField(choices=[('Healthy', 'Healthy'), ('Stressed', 'Stressed'), ('Poor', 'Poor'), ('Unknown', 'Unknown')], default='Healthy', max_length=50),
        ),
        migrations.AlterField(
            model_name='satellitescan',
            name='evi',
            field=models.FloatField(blank=True, help_text='Enhanced Vegetation Index', null=True, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(3)]),
        ),
        migrations.AlterField(
            model_name='satellitescan',
            name='image_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='satellitescan',
            name='ndvi',
            field=models.FloatField(blank=True, help_text='Normalized Difference Vegetation Index (-1 to 1)', null=True, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='satellitescan',
            name='raw_satellite_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='satellitescan',
            name='savi',
            field=models.FloatField(blank=True, help_text='Soil Adjusted Vegetation Index', null=True, validators=[django.core.validators.MinValueValidator(-1), django.core.validators.MaxValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='satellitescan',
            name='scan_id',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='satellitescan',
            name='soil_moisture',
            field=models.FloatField(blank=True, help_text='Soil moisture percentage', null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='satellitescan',
            name='verified_farm_size',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='ndvihistory',
            index=models.Index(fields=['date'], name='ndvi_histor_date_20b038_idx'),
        ),
        migrations.AddIndex(
            model_name='satellitescan',
            index=models.Index(fields=['satellite_type', '-acquisition_date'], name='satellite_s_satelli_39f8bf_idx'),
        ),
        migrations.AddIndex(
            model_name='satellitescan',
            index=models.Index(fields=['crop_health_status'], name='satellite_s_crop_he_66fcf8_idx'),
        ),
        migrations.AddIndex(
            model_name='satellitescan',
            index=models.Index(fields=['processing_status'], name='satellite_s_process_2f3539_idx'),
        ),
    ]
