# Generated by Django 5.2.10 on 2026-02-03 21:09

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('banks', '0001_initial'),
        ('farmers', '0002_farmernote_alter_farmer_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(help_text='Unique loan identifier (e.g., LN-2026-001234)', max_length=50, unique=True)),
                ('requested_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1000.00'))])),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=2, help_text='May differ from requested amount based on assessment', max_digits=12, null=True)),
                ('interest_rate', models.FloatField(help_text='Annual interest rate (%)', validators=[django.core.validators.MinValueValidator(2.0), django.core.validators.MaxValueValidator(36.0)])),
                ('interest_rate_cap', models.FloatField(blank=True, help_text='Maximum rate this loan can be charged (from bank policy at approval)', null=True)),
                ('repayment_period_months', models.IntegerField(help_text='Loan tenor in months (max 5 years)', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(60)])),
                ('loan_purpose', models.CharField(help_text="e.g., 'Seed purchase', 'Fertilizer', 'Equipment'", max_length=100)),
                ('pulse_score_at_application', models.IntegerField(help_text="Farmer's credit score when they applied")),
                ('climate_protected', models.BooleanField(default=False, help_text='True if this loan has received climate-triggered rate reduction')),
                ('climate_risk_at_application', models.CharField(blank=True, choices=[('low', 'Low Risk'), ('moderate', 'Moderate Risk'), ('high', 'High Risk'), ('critical', 'Critical Risk')], help_text='Climate risk level when loan was approved', max_length=20, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('disbursed', 'Disbursed'), ('repaid', 'Fully Repaid'), ('defaulted', 'Defaulted')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='When bank made approval/rejection decision', null=True)),
                ('disbursed_at', models.DateTimeField(blank=True, help_text='When funds were sent to farmer via M-Pesa', null=True)),
                ('satellite_verification_id', models.CharField(blank=True, help_text='Link to satellite scan that verified the farm', max_length=100, null=True)),
                ('api_response_time_ms', models.IntegerField(blank=True, help_text='Time taken for loan assessment', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to='banks.bank')),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to='farmers.farmer')),
            ],
            options={
                'db_table': 'loan_applications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ClimateRateAdjustment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('climate_event_id', models.CharField(help_text='Reference to ClimateAlert in climate app', max_length=100)),
                ('climate_severity', models.CharField(help_text="e.g., 'high', 'critical'", max_length=20)),
                ('climate_region', models.CharField(help_text='Geographic region affected', max_length=100)),
                ('old_rate', models.FloatField(help_text='Interest rate before adjustment')),
                ('new_rate', models.FloatField(help_text='Proposed/applied interest rate')),
                ('reason', models.TextField(help_text='Explanation of climate event and impact')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('applied', 'Applied'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(blank=True, help_text='When rate change took effect', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climate_adjustments', to='banks.bank')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_climate_adjustments', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climate_adjustments', to='loans.loanapplication')),
            ],
            options={
                'db_table': 'climate_rate_adjustments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('status_change', 'Status Change'), ('rate_change', 'Interest Rate Change'), ('disbursement', 'Loan Disbursed'), ('repayment', 'Payment Received'), ('restructure', 'Loan Restructured'), ('climate_adjustment', 'Climate Rate Adjustment')], max_length=50)),
                ('old_value', models.JSONField(blank=True, help_text='Previous state (JSON)', null=True)),
                ('new_value', models.JSONField(blank=True, help_text='New state (JSON)', null=True)),
                ('details', models.TextField(blank=True, help_text='Human-readable description')),
                ('triggered_by_system', models.BooleanField(default=False, help_text='True if automated, False if manual')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='loans.loanapplication')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'loan_audit_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.IntegerField(help_text='Instalment number (1, 2, 3...)')),
                ('due_date', models.DateField()),
                ('amount_due', models.DecimalField(decimal_places=2, help_text='Expected payment amount (EMI)', max_digits=12)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('paid_date', models.DateField(blank=True, help_text='When payment was received', null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('is_late', models.BooleanField(default=False, help_text='True if payment made after due_date')),
                ('days_late', models.IntegerField(default=0, help_text='Number of days overdue')),
                ('mpesa_transaction_id', models.CharField(blank=True, help_text='M-Pesa confirmation code', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='loans.loanapplication')),
            ],
            options={
                'db_table': 'loan_repayments',
                'ordering': ['loan', 'payment_number'],
            },
        ),
        migrations.CreateModel(
            name='LoanRestructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('climate_event', 'Climate Event'), ('default_risk', 'Default Risk Mitigation'), ('farmer_request', 'Farmer Hardship Request'), ('admin_decision', 'Administrative Decision')], max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Additional context')),
                ('old_interest_rate', models.FloatField()),
                ('old_repayment_period_months', models.IntegerField()),
                ('old_monthly_payment', models.DecimalField(decimal_places=2, max_digits=12)),
                ('old_outstanding_balance', models.DecimalField(decimal_places=2, help_text='How much was owed at restructure time', max_digits=12)),
                ('new_interest_rate', models.FloatField()),
                ('new_repayment_period_months', models.IntegerField()),
                ('new_monthly_payment', models.DecimalField(blank=True, decimal_places=2, help_text='Calculated once restructure is completed', max_digits=12, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='When new schedule was generated', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_restructures', to='banks.bank')),
                ('climate_adjustment', models.ForeignKey(blank=True, help_text='If restructure was triggered by climate event', null=True, on_delete=django.db.models.deletion.SET_NULL, to='loans.climaterateadjustment')),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restructures', to='loans.loanapplication')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_restructures', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'loan_restructures',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RepaymentSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_instalments', models.IntegerField(help_text='Number of monthly payments')),
                ('monthly_payment', models.DecimalField(decimal_places=2, help_text='Fixed EMI amount (Equated Monthly Instalment)', max_digits=12)),
                ('total_interest', models.DecimalField(decimal_places=2, help_text='Total interest to be paid over loan life', max_digits=12)),
                ('total_repayment', models.DecimalField(decimal_places=2, help_text='Principal + Interest', max_digits=12)),
                ('start_date', models.DateField(help_text='Date of first payment')),
                ('end_date', models.DateField(help_text='Date of final payment')),
                ('interest_rate_used', models.FloatField(help_text='Interest rate (%) used to generate this schedule')),
                ('is_current', models.BooleanField(default=True, help_text='False if loan has been restructured')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayment_schedules', to='loans.loanapplication')),
            ],
            options={
                'db_table': 'repayment_schedules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterestRatePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_rate', models.FloatField(help_text='Maximum rate (cannot exceed platform cap of 36.0%)', validators=[django.core.validators.MinValueValidator(2.0), django.core.validators.MaxValueValidator(36.0)])),
                ('min_rate', models.FloatField(help_text='Minimum rate for best-credit customers', validators=[django.core.validators.MinValueValidator(2.0), django.core.validators.MaxValueValidator(36.0)])),
                ('climate_reset_threshold', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('critical', 'Critical')], default='high', help_text='Climate severity level that triggers rate reset', max_length=20)),
                ('climate_floor_rate', models.FloatField(help_text='Rate to reset to during climate events', validators=[django.core.validators.MinValueValidator(2.0), django.core.validators.MaxValueValidator(36.0)])),
                ('auto_reset_enabled', models.BooleanField(default=True, help_text='If True, rate resets happen automatically. If False, requires bank approval.')),
                ('is_active', models.BooleanField(default=True, help_text='Only one policy per bank should be active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interest_rate_policies', to='banks.bank')),
            ],
            options={
                'verbose_name_plural': 'Interest Rate Policies',
                'db_table': 'interest_rate_policies',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['bank', 'is_active'], name='interest_ra_bank_id_c794d0_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='loanapplication',
            index=models.Index(fields=['farmer', '-created_at'], name='loan_applic_farmer__dc3c05_idx'),
        ),
        migrations.AddIndex(
            model_name='loanapplication',
            index=models.Index(fields=['bank', 'status'], name='loan_applic_bank_id_3eafd1_idx'),
        ),
        migrations.AddIndex(
            model_name='loanapplication',
            index=models.Index(fields=['status', '-created_at'], name='loan_applic_status_ed7068_idx'),
        ),
        migrations.AddIndex(
            model_name='loanapplication',
            index=models.Index(fields=['bank', 'climate_protected'], name='loan_applic_bank_id_79c374_idx'),
        ),
        migrations.AddIndex(
            model_name='climaterateadjustment',
            index=models.Index(fields=['loan', '-created_at'], name='climate_rat_loan_id_5293bb_idx'),
        ),
        migrations.AddIndex(
            model_name='climaterateadjustment',
            index=models.Index(fields=['bank', 'status'], name='climate_rat_bank_id_376e5f_idx'),
        ),
        migrations.AddIndex(
            model_name='climaterateadjustment',
            index=models.Index(fields=['status', '-created_at'], name='climate_rat_status_25cde1_idx'),
        ),
        migrations.AddIndex(
            model_name='climaterateadjustment',
            index=models.Index(fields=['climate_event_id'], name='climate_rat_climate_7b01e7_idx'),
        ),
        migrations.AddIndex(
            model_name='loanauditlog',
            index=models.Index(fields=['loan', '-created_at'], name='loan_audit__loan_id_406a3a_idx'),
        ),
        migrations.AddIndex(
            model_name='loanauditlog',
            index=models.Index(fields=['action', '-created_at'], name='loan_audit__action_896a2f_idx'),
        ),
        migrations.AddIndex(
            model_name='loanrepayment',
            index=models.Index(fields=['loan', 'is_paid'], name='loan_repaym_loan_id_dd39c4_idx'),
        ),
        migrations.AddIndex(
            model_name='loanrepayment',
            index=models.Index(fields=['due_date', 'is_paid'], name='loan_repaym_due_dat_b7e68a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='loanrepayment',
            unique_together={('loan', 'payment_number')},
        ),
        migrations.AddIndex(
            model_name='loanrestructure',
            index=models.Index(fields=['loan', '-created_at'], name='loan_restru_loan_id_15d1f3_idx'),
        ),
        migrations.AddIndex(
            model_name='loanrestructure',
            index=models.Index(fields=['bank', 'status'], name='loan_restru_bank_id_283fb9_idx'),
        ),
        migrations.AddIndex(
            model_name='loanrestructure',
            index=models.Index(fields=['reason', '-created_at'], name='loan_restru_reason_f18004_idx'),
        ),
        migrations.AddIndex(
            model_name='repaymentschedule',
            index=models.Index(fields=['loan', 'is_current'], name='repayment_s_loan_id_0bfe2d_idx'),
        ),
    ]
