# Generated by Django 5.2.10 on 2026-02-06 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auditlog_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs__user_id_7678dc_idx',
            old_name='audit_logs_user_id_e11c73_idx',
        ),
        migrations.RenameIndex(
            model_name='auditlog',
            new_name='audit_logs__action_4484d1_idx',
            old_name='audit_logs_action_f48619_idx',
        ),
        migrations.AlterModelTable(
            name='auditlog',
            table='audit_logs_accounts',
        ),
    ]
